services:
  - type: web
    name: ptc-library-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    autoDeploy: true