import React from 'react';
import { View, Image } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import * as Font from 'expo-font';

// Try to load a generated mapping of local PNG icon assets.
let iconSvgAssets = {};
let iconAssets = {};
try {
  // src/iconSvgAssets.js will be generated by scripts/generate-svg-assets.js
  // It maps iconName -> require('../assets/icons-svg/<name>.svg')
  // eslint-disable-next-line global-require, import/no-dynamic-require
  iconSvgAssets = require('../iconSvgAssets').default || {};
} catch (e) {
  iconSvgAssets = {};
}
try {
  // src/iconAssets.js maps iconName -> require('../assets/icons/<name>.png')
  // eslint-disable-next-line global-require, import/no-dynamic-require
  iconAssets = require('../iconAssets').default || {};
} catch (e) {
  iconAssets = {};
}

const FALLBACK_ICON = 'help-circle-outline';

const ICON_MAP = {
  menu: 'menu',
  close: 'close',
  'arrow-back': 'arrow-left',
  'chevron-down': 'chevron-down',
  'radio-button-on': 'radiobox-marked',
  refresh: 'refresh',
  book: 'book-outline',
  library: 'library-outline',
  catalog: 'bookshelf',
  person: 'account-outline',
  'person-circle': 'account-circle-outline',
  people: 'account-group-outline',
  'person-add': 'account-plus-outline',
  school: 'school-outline',
  'id-card': 'card-account-details-outline',
  'checkmark-circle': 'check-circle-outline',
  'checkmark-done-circle': 'check-all',
  'alert-circle': 'alert-circle-outline',
  'close-circle': 'close-circle-outline',
  time: 'clock-outline',
  hourglass: 'timer-sand',
  'arrow-undo-circle': 'undo-variant',
  scan: 'barcode-scan',
  'qr-code': 'qrcode',
  search: 'magnify',
  'swap-horizontal': 'swap-horizontal',
  'cloud-upload': 'cloud-upload-outline',
  image: 'image-outline',
  camera: 'camera-outline',
  'stats-chart': 'chart-bar',
  cash: 'cash',
  calendar: 'calendar-outline',
  'document-text': 'file-document-outline',
  briefcase: 'briefcase-outline',
  'shield-checkmark': 'shield-check-outline',
  notifications: 'bell-outline',
  'notifications-off': 'bell-off-outline',
  map: 'map-marker-outline',
  'phone-portrait': 'cellphone',
  sunny: 'white-balance-sunny',
  moon: 'moon-waning-crescent',
  settings: 'cog-outline',
  home: 'home-outline',
  speedometer: 'speedometer',
  'file-tray': 'tray-arrow-down',
  'log-out': 'logout',
};

const SUPPORTED_ICON_NAMES = new Set([
  FALLBACK_ICON,
  'menu',
  'close',
  'arrow-left',
  'chevron-down',
  'radiobox-marked',
  'refresh',
  'book-outline',
  'library-outline',
  'bookshelf',
  'account-outline',
  'account-circle-outline',
  'account-group-outline',
  'account-plus-outline',
  'school-outline',
  'card-account-details-outline',
  'check-circle-outline',
  'check-all',
  'alert-circle-outline',
  'close-circle-outline',
  'clock-outline',
  'timer-sand',
  'undo-variant',
  'barcode-scan',
  'qrcode',
  'magnify',
  'swap-horizontal',
  'cloud-upload-outline',
  'image-outline',
  'camera-outline',
  'chart-bar',
  'cash',
  'calendar-outline',
  'file-document-outline',
  'briefcase-outline',
  'shield-check-outline',
  'bell-outline',
  'bell-off-outline',
  'map-marker-outline',
  'cellphone',
  'white-balance-sunny',
  'moon-waning-crescent',
  'cog-outline',
  'home-outline',
  'speedometer',
  'tray-arrow-down',
  'logout',
]);

function normalizeIconName(name) {
  return String(name || '')
    .trim()
    .toLowerCase()
    .replace(/-outline$/, '');
}

function resolveIconName(name) {
  const normalized = normalizeIconName(name);
  const resolved = ICON_MAP[normalized] || String(name || '').trim();
  return SUPPORTED_ICON_NAMES.has(resolved) ? resolved : FALLBACK_ICON;
}

export default function Icon({ name, size = 20, color = '#000', style }) {
  const resolved = resolveIconName(name);
  // Prefer SVG asset if present
  if (iconSvgAssets && Object.prototype.hasOwnProperty.call(iconSvgAssets, resolved)) {
    const SvgComp = iconSvgAssets[resolved];
    const Comp = SvgComp && (SvgComp.default || SvgComp);
    if (Comp) {
      return <Comp width={size} height={size} fill={color} style={style} />;
    }
  }

  // If a local PNG asset exists for this resolved icon, render it next
  if (iconAssets && Object.prototype.hasOwnProperty.call(iconAssets, resolved)) {
    const src = iconAssets[resolved];
    return (
      <Image
        source={src}
        style={[{ width: size, height: size, tintColor: color }, style]}
        resizeMode="contain"
      />
    );
  }

  const fontLoaded = typeof Font.isLoaded === 'function' ? Font.isLoaded('material-community') : true;

  if (!fontLoaded) {
    // simple visual placeholder while icon font is not ready
    return <View style={[{ width: size, height: size, borderRadius: size / 6, backgroundColor: color, opacity: 0.12 }, style]} />;
  }

  return <MaterialCommunityIcons name={resolved} size={size} color={color} style={style} />;
}
